use_frameworks!

target 'HDRosaryTimeline_Example' do
  pod 'HDRosaryTimeline', :path => '../'

    target 'HDRosaryTimeline_Tests' do
        pod 'HDRosaryTimeline', :path => '../'
        pod 'Quick', '~> 1.2.0'
    end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.2'
    end
  end
end
