use_frameworks!

target 'HDRosaryTimeline_Example' do
  pod 'HDRosaryTimeline', :path => '../'

    target 'HDRosaryTimeline_Tests' do
        pod 'HDRosaryTimeline', :path => '../'
        pod 'Quick', '~> 1.2.0'
    end
end
